config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#new"
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  post 'proxy', to: 'admin/players#proxy'
  post 'refresh', to: 'admin/players#refresh'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :games do
      resources :communities
      get 'api', to: '/admin/communities#api'
    end
    resources :games
    resources :players
  end

  resources :communities do
    resource :reviews
  end
  resources :sessions
  resources :games
  resources :players
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :game, optional: true
  has_many :holes

  validates :name, presence: true, uniqueness: true
  validates :password, presence: true

  enum role: { admin: 1, participants: 2, tester: 3 }
  # admin: 実験管理者
  # participants: サクラ
  # tester: 被験者
end

app/controllers/admin/players_controller.rb
class Admin::PlayersController < Admin::ApplicationController
  before_action :authenticate_player

  def index
    @players = Player.all.order('created_at desc')
  end
  def show
    @player = Player.find(params[:id])
    @holes = @player.holes
    @win_holes = @holes.select{|hole| hole.out_come == true}
    @stay_holes = @holes.select{|hole| hole.stay? }
    if @holes.present?
      if @win_holes.present?
        @max_hand = @win_holes.max{|a, b| a.hand_before_type_cast <=> b.hand_before_type_cast}.hand
      else
        @max_hand = '- -'
      end
      @win_rate = @win_holes.length/@stay_holes.length.to_f * 100
    else
      @win_rate = '- -'
    end
  end

  def update
    @current_player.update(role: params[:become])
    flash[:notice] = "プレイヤー登録されました。"
    redirect_to player_path(@current_player)
  end

  def refresh
    p1 = Player.find_by(name: 'player1')
    p1.game_id = params[:game_id]
    p1.chip = 500
    p1.save
    p0 = Player.find_by(name: 'player0')
    p0.game_id = params[:game_id]
    p0.chip = 500
    p0.save
    redirect_to admin_games_path
  end

  def proxy
    session[:player_id] = params[:id]
    flash[:notice] = "代理ログインしました"
    redirect_to games_path
  end

  private

  def player_params
    params.require(:player).permit(:name, :password, :role)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :forbid_login_player, {only: [:new,:create]}
  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      session[:player_id] = @player.id
      flash[:notice] = "ユーザーが登録されました"
      redirect_to games_path
    else
      render new_player_path
    end
  end

  def show
    @player = @current_player
    @holes = @player.holes
    @win_holes = @holes.select{|hole| hole.out_come == true}
    @stay_holes = @holes.select{|hole| hole.stay? }
    if @holes.present?
      if @win_holes.present?
        @max_hand = @win_holes.max{|a, b| a.hand_before_type_cast <=> b.hand_before_type_cast}.hand
      else
        @max_hand = '- -'
      end
      @win_rate = @win_holes.length/@stay_holes.length.to_f * 100
    else
      @win_rate = '- -'
    end
  end

  def update
    @current_player.update(role: params[:become])
    flash[:notice] = "実験協力者登録されました。" if params[:become] == 'participants'
    flash[:notice] = "被験者登録されました。" if params[:become] == 'tester'
    redirect_to player_path(@current_player)
  end

  private

  def player_params
    params.require(:player).permit(:name, :password, :role)
  end
end

app/views/admin/players/index.html.slim
.content-header
  .container-fluid
    .row.mb-2
      .col-sm-6
        h1.m-0.text-dark
          | Players Table
.content
  .container-fluid
    .row
      .col-lg-12
        table.table.table-bordered.table-striped.dataTable role="grid"
          thead
            tr role="row"
              th ID
              th GAME_ID
              th プレイヤー名
              th 種別
              th チップ数
          tbody
            - @players.each do |player|
              tr role="row"
                td = player.id
                td = player.game_id
                td = link_to(player.name, admin_player_path(player))
                td = player.role
                td = player.chip

      .col-lg-6
        = form_tag refresh_path, :method => :post do
          = label_tag :game_id
          = number_field_tag :game_id
          = submit_tag "指定ゲームへplayerを移動させる"

app/views/admin/players/show.html.slim
.content-header
  .container-fluid
    .row.mb-2
      .col-sm-6
        h1.m-0.text-dark
          | プレイヤー詳細
      .col-sm-6
        = link_to '代理ログイン', proxy_path(id: "#{@player.id}"), method: :post, class: "btn btn-danger", data: { confirm: '代理ログインしても良いですか?' }

.content
  .container-fluid
    .row
      .card-body
        table.table.table-striped
          tbody
            tr
              th プレイヤー名
              th = @player.name
            tr
              th プレイヤー種別
              th = @player.role
            tr
              th 現在のチップ数
              th = @player.chip
            tr
              th.row
                .col-md-6
                  | 戦績
                .col-md-6
                  | 参加したラウンド数
              th = @holes.length
            tr
              th.row
                .col-md-6
                .col-md-6
                  | 最高あがりハンド
              th = @max_hand
            tr
              th.row
                .col-md-6
                .col-md-6
                  | 勝率
              th = number_to_percentage(@win_rate)