config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#new"
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  post 'proxy', to: 'admin/players#proxy'
  post 'refresh', to: 'admin/players#refresh'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :games do
      resources :communities
      get 'api', to: '/admin/communities#api'
    end
    resources :games
    resources :players
  end

  resources :communities do
    resource :reviews
  end
  resources :sessions
  resources :games
  resources :players
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :communities
  has_many :players
  validates :name, presence: true
end

app/controllers/admin/games_controller.rb
class Admin::GamesController < Admin::ApplicationController
  before_action :authenticate_player
  def index
    @games = Game.all
  end
  def show
    @game = Game.find(params[:id])
    @players = @game.players
  end
  def new
    @game = Game.new
  end

  def edit
  end
  def update
    @current_player.update(game_id: params[:id])
    redirect_to new_community_path
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to admin_games_path
    else
      render :new
    end
  end
  def destroy
    @game = Game.find(params[:id])
    @game.delete
    redirect_to admin_games_path
  end

  private

  def game_params
    params.require(:game).permit(:name)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_player

  def index
    @games = Game.all
  end
  def show
    @game = Game.find(params[:id])
    @players = @game.players
  end
  def new
    @game = Game.new
  end
  def update
    @current_player.update(game_id: params[:id], chip: 500)
    redirect_to new_community_path
  end

  def create
  end
end

app/views/admin/games/index.html.slim
.content-header
  .container-fluid
    .row.mb-2
      .col-sm-6
        h1.m-0.text-dark
          | ロビー
      .col-sm-6
        = link_to '新規テーブル追加', new_admin_game_path, class: "btn btn-success"
.content
  .container-fluid
    .row
      .col-lg-12
        table.table.table-bordered.table-striped.dataTable role="grid"
          thead
            tr role="row"
              th テーブル番号
              th テーブル名
              th 参加人数
              th
          tbody
            - @games.each do |game|
              tr role="row"
                td = game.id
                td = link_to(game.name, admin_game_path(game))
                td
                  - game.players.each do |player|
                    -if player.admin?
                      i.far.fa-user
                    -else
                      i.fas.fa-user
                td
                  -if @current_player.admin?
                    = link_to '削除', admin_game_path(game), method: :delete, class: "btn btn-danger"

app/views/admin/games/new.html.slim
.content-header
  .container-fluid
    .row.mb-2
      .col-sm-6
        h3.m-0.text-dark
          | 新規テーブル登録
.content
  .container-fluid
    .row
      .col-lg-6
        .form-body
          = form_for(@game, url: admin_games_path) do |f|
            - @game.errors.full_messages.each do |message|
              .form-error
                = message
            .form-group
              = f.text_field :name, class: 'form-control', placeholder: 'テーブル名'
            = f.submit "登録", class: 'btn btn-info'

app/views/admin/games/show.html.slim
.content-header
  .container-fluid
    .row.mb-2
      .col-lg-4
        h3.m-0.text-dark
          = @game.name
      .col-lg-3
        = link_to 'このテーブルに参加する', game_path, method: :put, class: "btn btn-success"
      .col-lg-5
        = link_to 'ログを見る', admin_game_communities_path(@game), class: "btn btn-warning"
.content
  .container-fluid
    .row
      .card-body
        .col-lg-6
          table.table.table-striped
            thead
              tr role="row"
                th 現在参加しているプレイヤー
                th
                  = @game.players.count{|player| !player.admin?}
            tbody
              - @game.players.each do |player|
                tr
                  - if player.admin?
                    th
                      i.far.fa-user
                        | 　ディーラー
                  - else
                    th
                      i.fas.fa-user
                        | 　参加プレイヤー
                  td = player.name