config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#new"
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  post 'proxy', to: 'admin/players#proxy'
  post 'refresh', to: 'admin/players#refresh'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :games do
      resources :communities
      get 'api', to: '/admin/communities#api'
    end
    resources :games
    resources :players
  end

  resources :communities do
    resource :reviews
  end
  resources :sessions
  resources :games
  resources :players
end

app/models/community.rb
class Community < ApplicationRecord
  include AasmCommunity
  has_many :cards, :as => :cardable
  has_many :holes
  has_one :review
  belongs_to :game
end

app/controllers/admin/communities_controller.rb
class Admin::CommunitiesController < Admin::ApplicationController
  # before_action :authenticate_player
  def index
    @game = Game.find(params[:game_id])
    @communities = @game.communities.order(created_at: :asc)
  end
  def api
    @game = Game.find(params[:game_id])
    @communities = @game.communities.order(created_at: :asc)
    @communities = @communities.map do |community|
      {
        id: community.id,
        flop_start: community.created_at.instance_eval { '%s.%03d' % [strftime('%H:%M:%S'), (usec / 1000.0).round] },
        river_start: community.state_histories.find_by(state: 'river')&.created_at&.instance_eval { '%s.%03d' % [strftime('%H:%M:%S'), (usec / 1000.0).round] },
        river_end: community.state_histories.find_by(state: 'showdown')&.created_at&.instance_eval { '%s.%03d' % [strftime('%H:%M:%S'), (usec / 1000.0).round] },
        flop_pod: community.flop_pod,
        river_pod: community.river_pod,
        finished: community.state_histories.find_by(state: 'finished')&.created_at&.instance_eval { '%s.%03d' % [strftime('%H:%M:%S'), (usec / 1000.0).round] }
      }
    end
    render json: @communities
  end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :authenticate_player
  include CreateDeck
  include HandJudgement

  def index
  end

  def new
    @game = @current_player.game
  end

  def create
    @game = @current_player.game
    if @current_player.admin?
      @community = @game.communities.create#コミュニティー作成
      @id = @community.id
      @game_id = @game.id
      @cards = shuffle(build) #シャッフルされた52枚のカード

      if @game_id == 0
        community_cards = drawCard(5) #コミュニティカード作成 #ランダム
        hole_cards = drawCard(2) #ホールカード作成
      else
        community_cards = drawCard(decide_community_cards(@id)) #コミュニティカード作成 #指定
        hole_cards = drawCard(decide_tester_cards(@id)) #ホールカード作成
      end
      community_cards.each do |c|
        @community.cards.create(suit:c.suit, number:c.number)
      end
      #被験者のホールカード決定
      @tester = @game.players.find_by(role: 'tester')
      @hole = @tester.holes.create(community_id: @id)

      hole_cards.each do |c|
        @hole.cards.create(suit:c.suit, number:c.number)
      end
      targetcards = @community.cards + @hole.cards
      @hole.hand = hand_judge(targetcards)
      @hole.save

      #サクラのホールカード決定
      @game.players.each do |player|
        next if !player.participants?
        @hole = player.holes.create(community_id: @id)
        if @game_id == 0
          hole_cards = drawCard(2)
        else
          if player.name == 'player0'
            hole_cards = drawCard(decide_player0_cards(@id)) #ホールカード作成
          elsif player.name == 'player1'
            hole_cards = drawCard(decide_player1_cards(@id)) #ホールカード作成
          end
        end
        hole_cards.each do |c|
          @hole.cards.create(suit:c.suit, number:c.number)
        end
        targetcards = @community.cards + @hole.cards
        @hole.hand = hand_judge(targetcards)
        @hole.save
      end
      CommunityChannel.broadcast_to(@current_player.game, { message: 'start' })
    else
      @community = @game.communities.last
      @community.created_at = Time.now
      @community.save
    end
    redirect_to community_path(@community)
  end

  def show
    @community = Community.find(params[:id])
    @player_holes = []
    @community.holes.each do |hole|
      @player_holes[2] = hole if hole.player.tester?
      @player_holes[1] = hole if hole.player.name == 'player0'
      @player_holes[0] = hole if hole.player.name == 'player1'
    end
  end
  def update
  end
  def destroy
    @current_player.game_id = nil
    @current_player.save
    redirect_to games_path
  end

  private
  def decide_player0_cards(id)
    case id % 15
    when 1 # 3ワンペア
      return [['s',4],['h',11]]
    when 2 # ノーペア
      return [['h',10],['s',12]]
    when 3 # ノーペア
      return [['c',5],['h',2]]
    when 4 # 4 ワンペア
      return [['h',11],['s',7]]
    when 5 # 3 10 ツーペア
      return [['h',12],['c',2]]
    when 6 # 4 ワンペア
      return [['d',9],['h',4]]
    when 7 # ノーペア
      return [['c',1],['s',10]]
    when 8 # 5 7 ツーペア
      return [['d',10],['d',3]]
    when 9 # 2 ワンペア
      return [['c',7],['s',7]]
    when 10 # 8ハイフルハウス
      return [['c',10],['h',10]]
    when 11 # 11 ワンペア
      return [['h',8],['s',11]]
    when 12 # 9 ストレート
      return [['h',13],['s',6]]
    when 13 # ノーペア
      return [['d',1],['h',13]]
    when 14 #ダイヤフラッシュ
      return [['c',8],['s',2]]
    when 0 # 10 ワンペア
      return [['h',3],['h',2]]
    end
  end
  def decide_player1_cards(id)
    case id % 15
    when 1 # 3ワンペア
      return [['c',6],['d',10]]
    when 2 # ノーペア
      return [['c',7],['s',6]]
    when 3 # ノーペア
      return [['s',8],['h',11]]
    when 4 # 4 ワンペア
      return [['d',2],['d',5]]
    when 5 # 3 10 ツーペア
      return [['d',4],['h',6]]
    when 6 # 4 ワンペア
      return [['h',12],['s',10]]
    when 7 # ノーペア
      return [['d',9],['d',13]]
    when 8 # 5 7 ツーペア
      return [['c',4],['c',9]]
    when 9 # 2 ワンペア
      return [['h',12],['h',2]]
    when 10 # 8ハイフルハウス
      return [['c',12],['d',6]]
    when 11 # 11 ワンペア
      return [['c',2],['c',5]]
    when 12 # 9 ストレート
      return [['s',8],['d',10]]
    when 13 # ノーペア
      return [['h',9],['s',7]]
    when 14 #ダイヤフラッシュ
      return [['d',1],['d',5]]
    when 0 # 10 ワンペア
      return [['c',11],['c',1]]
    end
  end
  def decide_community_cards(id)
    case id % 15
    when 1 # 3ワンペア
      return [['h',13],['d',3],['h',7],['s',5],['s',3]]
    when 2 # ノーペア
      return [['d',7],['h',11],['h',1],['h',6],['s',13]]
    when 3 # ノーペア
      return [['h',1],['d',5],['c',8],['d',4],['s',13]]
    when 4 # 4 ワンペア
      return [['h',7],['h',1],['c',6],['c',8],['s',2]]
    when 5 # 3 10 ツーペア
      return [['c',11],['s',3],['s',10],['c',9],['d',6]]
    when 6 # 4 ワンペア
      return [['c',11],['s',9],['d',13],['c',4],['s',5]]
    when 7 # ノーペア
      return [['d',2],['s',5],['s',11],['c',9],['d',1]]
    when 8 # 5 7 ツーペア
      return [['d',13],['h',7],['h',5],['d',5],['h',4]]
    when 9 # 2 ワンペア
      return [['s',12],['s',2],['s',3],['d',2],['h',1]]
    when 10 # 8ハイフルハウス
      return [['d',8],['c',5],['c',8],['s',1],['s',5]]
    when 11 # 11 ワンペア
      return [['h',4],['h',11],['h',7],['d',11],['d',6]]
    when 12 # 9 ストレート
      return [['h',6],['c',9],['d',11],['d',7],['h',9]]
    when 13 # ノーペア
      return [['s',12],['h',2],['d',5],['h',7],['c',11]]
    when 14 #ダイヤフラッシュ
      return [['h',12],['d',3],['d',6],['d',13],['c',6]]
    when 0 # 10 ワンペア
      return [['h',4],['s',3],['d',12],['d',5],['s',10]]
    end
  end
  def decide_tester_cards(id)
    case id % 15
    when 1
      return [['h',5],['h',9]]
    when 2
      return [['h',4],['c',10]]
    when 3
      return [['s',6],['h',13]]
    when 4
      return [['h',4],['c',4]]
    when 5
      return [['d',3],['c',10]]
    when 6
      return [['s',4],['c',7]]
    when 7
      return [['d',7],['h',3]]
    when 8
      return [['c',7],['s',10]]
    when 9
      return [['c',4],['c',10]]
    when 10
      return [['s',12],['h',8]]
    when 11
      return [['d',9],['c',3]]
    when 12
      return [['c',5],['d',8]]
    when 13
      return [['d',10],['d',8]]
    when 14
      return [['d',12],['d',11]]
    when 0
      return [['c',10],['d',7]]
    end
  end

end

app/views/communities/_admin_action_field.html.slim
- if @admin == @current_player
  - @admin_cards.each do |card|
    .hole_card
      img src="/z02.png" width="70" height="105"
      .show_hole_card
        img src="/#{card.suit}#{card.number}.png" width="70" height="105"
  .player_action_field
    div id="#{@admin_name}_call_btn" class='call_field'
      .btn.btn-block.btn-warning
        | コール
    .drop_btn.btn.btn-block.btn-danger
      | 降りる
- else
  - @admin_cards.each do |card|
    .hole_card
      img src="/z02.png" width="70" height="105"
      .others_hole_card
        img src="/#{card.suit}#{card.number}.png" width="70" height="105"
  .player_action_field
    div id="#{@admin_name}_call_btn" class='others_call_field'
      .btn.btn-block.btn-warning.disabled
        | コール
    .btn.btn-block.btn-danger.disabled
      | 降りる

app/views/communities/_player_action_field.html.slim
- if player == @current_player
  - player_cards.each do |card|
    .hole_card
      .show_hole_card[style='display:inline-block;']
        img src="/#{card.suit}#{card.number}.png" width="70" height="105"
  .player_action_field[style="visibility: hidden;"]
    div id="#{player_name}_call_btn" class='call_field'
      .btn.btn-block.btn-danger.active
        | アクション
- else
  - player_cards.each do |card|
    .hole_card
      img src="/z02.png" width="70" height="105"
      .others_hole_card
        img src="/#{card.suit}#{card.number}.png" width="70" height="105"
  .player_action_field[style="visibility: hidden;"]
    div id="#{player_name}_call_btn" class='others_call_field'
      .btn.btn-block.btn-danger.disabled
        | アクション

app/views/communities/new.html.slim
.container
  h3.text-center
    | ディーラーの指示をおまちください


  .text-center
    - if @current_player.admin?
      .admin_start_btn
        = button_to "ゲーム開始", communities_path, method: :post, class:'btn btn-success'
    - else
      .player_start_btn
        = button_to "ゲーム開始", communities_path, method: :post, class:'btn btn-success'
    = button_to 'ロビーへ戻る', community_path(@game), method: :delete, class:'btn btn-success', data: { confirm: '退出しますがよろしいですか?' }
    = link_to 'ロビーへ立ち寄る', games_path, class:'btn btn-success', data: { confirm: '立ち寄りますか?' }

app/views/communities/show.html.slim
.container
  = hidden_field_tag :id, @community.game.id, class:'game-number'
  p.state_text.text-center[style='margin-top:150px;']
    | フロップです。
  .dealer-action.text-center
    .row
      - if @current_player.admin?
        .col-sm-4
          .dealer_btn.btn.btn-block.btn-danger
           | アクション
        .col-sm-4
          .admin_start_btn
            = button_to '次のラウンドへ', communities_path, method: :post, class:'btn btn-block btn-success'
        .col-sm-4
          = button_to 'ロビーへ戻る', community_path, method: :delete, class:'btn btn-block btn-success'
      - elsif @current_player.participants?
        .col-sm-12
          .player_start_btn
            = button_to '次のラウンドへ', communities_path, method: :post, class:'btn btn-block btn-success'
      - else
        .col-sm-12
          .player_start_btn
            = link_to '次のラウンドへ', communities_path, method: :post, class:'btn btn-block btn-success'

  .text-center.communities_card_field
    .community_card_field
      .pod_chip_number
        i.fas.fa-coins
          input.chip_num[value=@community.pod disabled='']
      - @community.cards.each_with_index do |card, index|
        .community_card
          img src="/z02.png" width="70" height="105"
          div id="card#{index}" class="show_community_card"
            img src="/#{card.suit}#{card.number}.png" width="70" height="105"

  .text-center.row
    - @player_holes.each do |hole|
      .col-4.player_field
        .player_raise_field
          i.fas.fa-coins
            input.chip_num[value=0 disabled='']
        .player_hole_card
          = hole.player.name
        .player_chip_number
          i.fas.fa-piggy-bank
            input.chip_num[value=hole.player.chip disabled='']
        div id="#{hole.player.name}_card_field" class='hole_card_field'
          h5.show_hand_name
            = hole.hand
          = render 'player_action_field', player: hole.player, player_name: hole.player.name, player_cards: hole.cards